### ISSUE TITLE
CSVDataloader problem

### ISSUE THREAD

**Issue by yujiangsenior** [AndreWeiner/ofw2022_dmd_training#1]
Hi there, I am trying to follow an example of DMD, as 
 follows. https://github.com/AndreWeiner/ofw2022_dmd_training/blob/main/dmd_flowtorch.ipynb  But the CSVDataloader could never be able to load the surface1 dataset succesfully, with the problem as follows. 
Could you please check with the issue? Thanks a million! 

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[35], line 2
      1 path = r'surface1'
----> 2 loader = CSVDataloader.from_foam_surface(path, "U_plane_xy.raw")
      3 times = loader.write_times

File E:\softwares\Anaconda3\envs\pyflowt\lib\site-packages\flowtorch\data\csv_dataloader.py:200, in CSVDataloader.from_foam_surface(cls, path, file_name, header, dtype)
    180 """Create CSVDataloader instance to load OpenFOAM surface sample data.
    181 
    182 The class method simplifies to load data generated by OpenFOAM's
   (...)
    197 
    198 """
    199 folders = glob(f"{path}/*")
--> 200 times = sorted(
    201     [folder.split("/")[-1] for folder in folders], key=float
    202 )
    203 filepath = join(path, times[0], file_name)
    204 with open(filepath, "r") as surface:

ValueError: could not convert string to float: 'surface1\\30.06'

**Comment by AndreWeiner** [comment]
Should be fixed; see [this issue](https://github.com/FlowModelingControl/flowtorch/issues/33).
Best regards,
Andre
